package com.carecircle.domain.patient.mapper;

import com.carecircle.domain.patient.Patient;
import com.carecircle.domain.patient.dto.PatientDto;
import org.mapstruct.*;

// =============================================================================
// 🧠 WHAT IS MAPSTRUCT?
//
// MapStruct auto-generates the boring conversion code between
// Entity ↔ DTO at COMPILE TIME (not runtime like reflection-based tools).
//
// Without MapStruct you'd write:
//   PatientDto.Response dto = new PatientDto.Response();
//   dto.setId(patient.getId());
//   dto.setFullName(patient.getFullName());
//   dto.setDateOfBirth(patient.getDateOfBirth());
//   ... 10 more lines ...
//
// With MapStruct you write this interface and it generates that code for you.
// Check target/generated-sources after build to see the generated class.
//
// PERFORMANCE: Since it's compile-time code generation (not reflection),
// it's as fast as hand-written code. This is why companies use it over
// ModelMapper or ObjectMapper for entity conversion.
// =============================================================================

@Mapper(
        componentModel = "spring",        // Makes this a Spring @Component (injectable)
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
        // IGNORE means: if a field in source is null, don't overwrite the target.
        // Critical for PATCH/PUT — don't wipe fields the client didn't send.
)
public interface PatientMapper {

    // Entity → Response DTO
    // 🧠 @Mapping: field names differ between entity and DTO.
    // "organization.name" = navigate the relationship to get org name.
    @Mapping(source = "organization.name", target = "organizationName")
    PatientDto.Response toResponse(Patient patient);

    // Entity → Summary DTO (lighter, for list endpoints)
    PatientDto.Summary toSummary(Patient patient);

    // CreateRequest DTO → Entity
    // 🧠 "ignore" these fields because:
    // - id: generated by DB, never from client input
    // - organization: set by service from security context, not from request body
    // - createdAt/updatedAt: managed by @CreatedDate/@LastModifiedDate
    // - isActive: defaults to true, not client-controlled on create
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "organization", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "active", ignore = true)
    Patient toEntity(PatientDto.CreateRequest request);

    // UpdateRequest → existing Entity (partial update)
    // 🧠 @MappingTarget: instead of creating a NEW entity,
    // MapStruct updates the EXISTING entity passed in.
    // Combined with IGNORE null strategy above, this gives us
    // safe partial updates — only update what was sent.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "organization", ignore = true)
    @Mapping(target = "dateOfBirth", ignore = true)  // immutable after creation
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "active", ignore = true)
    void updateEntity(PatientDto.UpdateRequest request, @MappingTarget Patient patient);
}